# Changes here will be overwritten by Copier
_commit: 78c3b92
_src_path: ../../templates/copier-f2dv-project
author_email: hello@f2dv.com
author_name: Donald Mellenbruch
docs_slides_url: https://www.f2dv.com/s/argparse-tui
docs_url: https://www.f2dv.com/r/argparse-tui
funding_url: https://www.f2dv.com/fund
home_domain: f2dv.com
home_page: https://www.f2dv.com
is_minimal: false
is_python: true
license_type: MIT
package_name: argparse_tui
project_description: Your Argparse CLI, now with a TUI.
project_name: argparse-tui
python_version: '3.8'
repo_name: fresh2dev/argparse-tui
repo_owner: fresh2dev
repo_url: https://www.github.com/fresh2dev/argparse-tui

