---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      # - id: check-json
      - id: check-shebang-scripts-are-executable
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: local
    hooks:
    - id: ruff-format
      name: Ruff format
      language: system
      types: [python]
      # pass_filenames: false
      entry: >
        uvx ruff format

    - id: pylint
      name: Pylint
      language: system
      types: [python]
      pass_filenames: false
      entry: >
        uvx --with pylint-venv pylint --init-hook='import pylint_venv; pylint_venv.inithook(force_venv_activation=True)' --disable=R,C,W0511 ./src

    - id: docsig
      name: Lint Docstrings
      language: system
      types: [python]
      pass_filenames: false
      entry: >
        uvx docsig ./src

    # - id: pyrefly
    #   name: Check Types
    #   language: system
    #   types: [python]
    #   pass_filenames: false
    #   entry: >
    #       uvx pyrefly check --output-format min-text ./src
