site_name: "argparse-tui"
site_description: "argparse-tui Docs"
site_url: "https://www.f2dv.com/r/argparse-tui"
repo_url: "https://www.github.com/fresh2dev/argparse-tui"
repo_name: "fresh2dev/argparse-tui"
edit_uri: "edit/main/docs"
# edit_uri_template: "src/branch/main/docs/{path}"
docs_dir: "docs"

copyright: '<a href="https://www.fresh2.dev/"><img src="https://img.fresh2.dev/fresh2dev.svg" style="height: 3em; margin-right: 1em; filter: invert(100%);"></img></a> &copy; 2023 <a rel="license" target="_blank" href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="Creative Commons License" style="border-width:0; margin-left: 1em;" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" /></a>'
extra:
  generator: false
  social: []
    # - name: Fresh2.dev
    #   icon: "material/home"
    #   link: 'https://www.fresh2.dev/'

## https://www.mkdocs.org/user-guide/writing-your-docs/#configure-pages-and-navigation
nav:
  - Home: index.md
  - Reference: reference/
  - Changelog: changelog.md
  - License: license.md
  - '<- f2dv.com':
      - '/projects': 'https://www.f2dv.com/projects/'
      # - '/fund': 'https://www.f2dv.com/fund/'

watch:
  - ./README.md
  - ./CHANGELOG.md
  - ./LICENSE
  - ./src

theme:
  name: material
  language: en
  custom_dir: config/overrides
  palette:
    # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#primary-color
    - scheme: slate
      primary: deep purple
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
    - scheme: default
      primary: deep purple
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
  features:
    - content.code.copy
    - content.code.annotate
    - navigation.instant
    - navigation.indexes
    - navigation.expand
    - navigation.top
    - announce.dismiss
    # - navigation.footer

# extra_css:
#   - css/extra.css

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 3
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.magiclink:
      hide_protocol: true
      repo_url_shortener: false
      social_url_shortener: false
  - pymdownx.saneheaders
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.snippets

plugins:
  - search
  - include_dir_to_nav
  - autorefs
  - mkdocs-jupyter:
      ignore_h1_titles: True
      include_source: True
      execute: false
      remove_tag_config:
        remove_input_tags:
          - hidden
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: ["src"]
          options:
            docstring_section_style: spacy
            docstring_style: google
            members_order: 'alphabetical'  # 'source'
            merge_init_into_class: true
            separate_signature: true
            show_bases: false
            show_category_heading: true
            show_if_no_docstring: false
            show_object_full_path: false
            show_root_full_path: false
            show_root_heading: false
            show_root_members_full_path: false
            show_root_toc_entry: false
            show_signature: true
            show_signature_annotations: true
            show_source: true
            show_submodules: false
            signature_corssrefs: true
            unwrap_annotated: true
